clone_depth: 5

environment:
  QTDIR: C:\Qt\5.7\msvc2015_64
  GENERATOR: "Visual Studio 14 Win64"

configuration:
  - Release
  - Debug

platform:
  - x64

before_build:
  - mkdir build
  - cd build
  - set PATH=%QTDIR%\bin;%PATH%
  - ps: ./scripts/build_frameworks.ps1
  - cmd: if "%configuration%"=="Debug" cmake "-G%GENERATOR%" -DCMAKE_PREFIX_PATH="%QTDIR%" ..
  - cmd: if "%configuration%"=="Release"   cmake "-G%GENERATOR%" -DCMAKE_PREFIX_PATH="%QTDIR%" ..

build:
  parallel: true
  project: C:\projects\nodeeditor\build\chigraph.sln
