clone_depth: 5

environment:
  QTDIR: C:\Qt\5.7\msvc2015_64
  GENERATOR: "Visual Studio 14 Win64"

configuration:
  - Release
  - Debug

platform:
  - x64

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - ps: $path = $pwd
  - ps: .\scripts\download_llvm.ps1 "$Env:configuration"
  - ps: cd $path
  - ps: .\scripts\build_frameworks.ps1 "$Env:QTDIR" "$Env:configuration" ""
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE="%configuration%" -DCMAKE_PREFIX_PATH="%QTDIR%" ..

build:
  parallel: true
  project: C:\projects\chigraph\build\chigraph.sln
