clone_depth: 5

environment:
  QTDIR: C:\Qt\5.7\msvc2015_64
  GENERATOR: "Visual Studio 14 Win64"

configuration:
  - Release
  - Debug

platform:
  - x64

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - ps: .\scripts\build_frameworks.ps1 -DCMAKE_BUILD_TYPE="$Env:configuration" -DCMAKE_PREFIX_PATH="$Env:QTDIR"
  - mkdir build
  - cd build
  - cmake "-G%GENERATOR%" -DCMAKE_BUILD_TYPE="%configuration%" -DCMAKE_PREFIX_PATH="%QTDIR%" ..

build:
  parallel: true
  project: C:\projects\nodeeditor\build\chigraph.sln
