sudo: required
language: cpp
dist: trusty
cache:
  directories:
    - third_party/kf5

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:beineri/opt-qt562-trusty'
      - sourceline: 'ppa:beineri/opt-qt571-trusty'
      
matrix: 
  include: 
  
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.9 TEST_COV=YES
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.9
    - env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.9
    
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.7
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.7
    
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=562 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-5         C_COMPILER=gcc-5      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=g++-6         C_COMPILER=gcc-6      BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.7   C_COMPILER=clang-3.7  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.8   C_COMPILER=clang-3.8  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Debug     QT_VERSION=571 LLVM_VERSION=3.8
    #- env: CXX_COMPILER=clang++-3.9   C_COMPILER=clang-3.9  BUILD_TYPE=Release   QT_VERSION=571 LLVM_VERSION=3.8
    
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7
      env: BUILD_TYPE=Release
    - os: osx
      osx_image: xcode7
      env: BUILD_TYPE=Release
      
      
    

install: 
  - ./travis/install.sh

script:
  - ./travis/build.sh
